export const problemsListData = {
  data: [
    {
      id: 1001,
      execution_number: 1002,
      problem_name: 'Keccak256 Hash',
      user_name: 'Polyhedra Network',
      user_avatar: 'user_avatar_svg',
      create_time: 'Jul 15, 2024, 16:58:53 (UTC+08:00)',
    },
    {
      id: 1002,
      execution_number: 6732,
      problem_name: 'SHA256 Hash',
      user_name: 'Polyhedra Network',
      user_avatar: 'user_avatar_svg',
      create_time: 'Jul 15, 2024, 18:58:53 (UTC+08:00)',
    },
    {
      id: 1003,
      execution_number: 3600,
      problem_name: 'ECDSA Signature',
      user_name: 'Polyhedra Network',
      user_avatar: 'user_avatar_svg',
      create_time: 'Jul 15, 2024, 18:59:53 (UTC+08:00)',
    },
    {
      id: 1004,
      execution_number: 3600,
      problem_name: 'Poseidon2 Hash M31',
      user_name: 'Polyhedra Network',
      user_avatar: 'user_avatar_svg',
      create_time: 'Jul 15, 2024, 18:59:53 (UTC+08:00)',
    },
    {
      id: 1005,
      execution_number: 3600,
      problem_name: 'Poseidon2 Hash BN254',
      user_name: 'Polyhedra Network',
      user_avatar: 'user_avatar_svg',
      create_time: 'Jul 15, 2024, 18:59:53 (UTC+08:00)',
    },
  ],
  total: 5,
};

export const problemsDetailData = [
  {
    id: 1001,
    execution_number: 1002,
    problem_name: 'Keccak256 Hash',
    user_name: 'Polyhedra Network',
    user_avatar: 'user_avatar_svg',
    create_time: 'Jul 15, 2024, 16:58:53 (UTC+08:00)',
    description: '',
    // desc: 'Test vectors <a href="https://emn178.github.io/online-tools/keccak_256.html">https://emn178.github.io/online-tools/keccak_256.html</a>',
    submissionsTableData: [
      {
        id: 1,
        prover_name: 'Alpha,algo 1',
        proof_system: 'Alpha',
        algorithm: 'algo 1',
        status: 'pending',
        setup_time: 3.5,
        witness_generation_time: 3.5,
        proof_generation_time: 3.5,
        verify_time: 3.5,
        peak_memory: 644,
        proof_size: 542,
      },
      {
        id: 2,
        prover_name: 'Alpha,algo 2',
        proof_system: 'Alpha',
        algorithm: 'algo 2',
        status: 'running',
        setup_time: 6.5,
        witness_generation_time: 3.5,
        proof_generation_time: 8.5,
        verify_time: 5.5,
        peak_memory: 1044,
        proof_size: 642,
      },
      {
        id: 3,
        prover_name: 'Alpha,algo 3',
        proof_system: 'Alpha',
        algorithm: 'algo 3',
        status: 'completed',
        setup_time: 12.5,
        witness_generation_time: 6.5,
        proof_generation_time: 10.5,
        verify_time: 3.5,
        peak_memory: 1644,
        proof_size: 202,
      },
      {
        id: 4,
        prover_name: 'Beta,algo 1',
        proof_system: 'Beta',
        algorithm: 'algo 1',
        status: 'completed',
        setup_time: 12.5,
        witness_generation_time: 6.5,
        proof_generation_time: 10.5,
        verify_time: 3.5,
        peak_memory: 1444,
        proof_size: 202,
      },
      {
        id: 5,
        prover_name: 'Beta,algo 2',
        proof_system: 'Beta',
        algorithm: 'algo 2',
        status: 'completed',
        setup_time: 16.5,
        witness_generation_time: 2.5,
        proof_generation_time: 6.5,
        verify_time: 7.5,
        peak_memory: 1404,
        proof_size: 502,
      },
      {
        id: 6,
        prover_name: 'Gamma,algo 1',
        proof_system: 'Gamma',
        algorithm: 'algo 1',
        status: 'completed',
        setup_time: 16.5,
        witness_generation_time: 2.5,
        proof_generation_time: 6.5,
        verify_time: 7.5,
        peak_memory: 1204,
        proof_size: 502,
      },
      {
        id: 7,
        prover_name: 'Gamma,algo 2',
        proof_system: 'Gamma',
        algorithm: 'algo 2',
        status: 'completed',
        setup_time: 13.5,
        witness_generation_time: 2.5,
        proof_generation_time: 6.5,
        verify_time: 7.5,
        peak_memory: 1304,
        proof_size: 102,
      },
    ],
  },
  {
    id: 1002,
    execution_number: 6732,
    problem_name: 'SHA256 Hash',
    user_name: 'Polyhedra Network',
    user_avatar: 'user_avatar_svg',
    description: 'sha256_hash_details.md',
    create_time: 'Jul 15, 2024, 18:58:53 (UTC+08:00)',
    // desc: 'Test vectors <a href="https://emn178.github.io/online-tools/sha256.html">https://emn178.github.io/online-tools/sha256.html</a>',
    submissionsTableData: [
      {
        id: 1,
        prover_name: 'Alpha,algo 1',
        proof_system: 'Alpha',
        algorithm: 'algo 1',
        status: 'pending',
        setup_time: 3.5,
        witness_generation_time: 3.5,
        proof_generation_time: 3.5,
        verify_time: 3.5,
        peak_memory: 624,
        proof_size: 542,
      },
      {
        id: 2,
        prover_name: 'Alpha,algo 2',
        proof_system: 'Alpha',
        algorithm: 'algo 2',
        status: 'running',
        setup_time: 6.5,
        witness_generation_time: 3.5,
        proof_generation_time: 8.5,
        verify_time: 5.5,
        peak_memory: 1344,
        proof_size: 542,
      },
      {
        id: 3,
        prover_name: 'Alpha,algo 3',
        proof_system: 'Alpha',
        algorithm: 'algo 3',
        status: 'completed',
        setup_time: 7.5,
        witness_generation_time: 6.5,
        proof_generation_time: 10.5,
        verify_time: 3.5,
        peak_memory: 1644,
        proof_size: 202,
      },
      {
        id: 4,
        prover_name: 'Beta,algo 1',
        proof_system: 'Beta',
        algorithm: 'algo 1',
        status: 'completed',
        setup_time: 8.5,
        witness_generation_time: 6.5,
        proof_generation_time: 10.5,
        verify_time: 3.5,
        peak_memory: 1244,
        proof_size: 502,
      },
      {
        id: 5,
        prover_name: 'Beta,algo 2',
        proof_system: 'Beta',
        algorithm: 'algo 2',
        status: 'completed',
        setup_time: 9.5,
        witness_generation_time: 2.5,
        proof_generation_time: 6.5,
        verify_time: 7.5,
        peak_memory: 1504,
        proof_size: 402,
      },
      {
        id: 6,
        prover_name: 'Gamma,algo 1',
        proof_system: 'Gamma',
        algorithm: 'algo 1',
        status: 'completed',
        setup_time: 13.5,
        witness_generation_time: 2.5,
        proof_generation_time: 6.5,
        verify_time: 7.5,
        peak_memory: 1604,
        proof_size: 252,
      },
      {
        id: 7,
        prover_name: 'Gamma,algo 2',
        proof_system: 'Gamma',
        algorithm: 'algo 2',
        status: 'completed',
        setup_time: 12.5,
        witness_generation_time: 2.5,
        proof_generation_time: 6.5,
        verify_time: 7.5,
        peak_memory: 1404,
        proof_size: 232,
      },
    ],
  },
  {
    id: 1003,
    execution_number: 3600,
    problem_name: 'ECDSA Signature',
    user_name: 'Polyhedra Network',
    user_avatar: 'user_avatar_svg',
    create_time: 'Jul 15, 2024, 18:59:53 (UTC+08:00)',
    description: '',
    // desc: 'Test vectors <a href="https://emn178.github.io/online-tools/ecdsa_verify.html">https://emn178.github.io/online-tools/ecdsa_verify.html</a>',
    submissionsTableData: [
      {
        id: 1,
        prover_name: 'Alpha,algo 1',
        proof_system: 'Alpha',
        algorithm: 'algo 1',
        status: 'pending',
        setup_time: 3.5,
        witness_generation_time: 3.5,
        proof_generation_time: 3.5,
        verify_time: 3.5,
        peak_memory: 444,
        proof_size: 242,
      },
      {
        id: 2,
        prover_name: 'Alpha,algo 2',
        proof_system: 'Alpha',
        algorithm: 'algo 2',
        status: 'running',
        setup_time: 6.5,
        witness_generation_time: 3.5,
        proof_generation_time: 8.5,
        verify_time: 5.5,
        peak_memory: 1044,
        proof_size: 642,
      },
      {
        id: 3,
        prover_name: 'Alpha,algo 3',
        proof_system: 'Alpha',
        algorithm: 'algo 3',
        status: 'completed',
        setup_time: 12.5,
        witness_generation_time: 6.5,
        proof_generation_time: 10.5,
        verify_time: 3.5,
        peak_memory: 1244,
        proof_size: 402,
      },
      {
        id: 4,
        prover_name: 'Beta,algo 1',
        proof_system: 'Beta',
        algorithm: 'algo 1',
        status: 'completed',
        setup_time: 10.5,
        witness_generation_time: 6.5,
        proof_generation_time: 10.5,
        verify_time: 3.5,
        peak_memory: 1544,
        proof_size: 262,
      },
      {
        id: 5,
        prover_name: 'Beta,algo 2',
        proof_system: 'Beta',
        algorithm: 'algo 2',
        status: 'completed',
        setup_time: 16.5,
        witness_generation_time: 2.5,
        proof_generation_time: 6.5,
        verify_time: 7.5,
        peak_memory: 1444,
        proof_size: 282,
      },
      {
        id: 6,
        prover_name: 'Gamma,algo 1',
        proof_system: 'Gamma',
        algorithm: 'algo 1',
        status: 'completed',
        setup_time: 11.5,
        witness_generation_time: 2.5,
        proof_generation_time: 6.5,
        verify_time: 7.5,
        peak_memory: 1204,
        proof_size: 262,
      },
      {
        id: 7,
        prover_name: 'Gamma,algo 2',
        proof_system: 'Gamma',
        algorithm: 'algo 2',
        status: 'completed',
        setup_time: 12.5,
        witness_generation_time: 2.5,
        proof_generation_time: 6.5,
        verify_time: 7.5,
        peak_memory: 1204,
        proof_size: 232,
      },
    ],
  },
  {
    id: 1004,
    execution_number: 3600,
    problem_name: 'Poseidon2 Hash M31',
    user_name: 'Polyhedra Network',
    user_avatar: 'user_avatar_svg',
    create_time: 'Jul 15, 2024, 18:59:53 (UTC+08:00)',
    description: '',
    // desc: '--',
    submissionsTableData: [
      {
        id: 1,
        prover_name: 'Alpha,algo 1',
        proof_system: 'Alpha',
        algorithm: 'algo 1',
        status: 'pending',
        setup_time: 3.5,
        witness_generation_time: 3.5,
        proof_generation_time: 3.5,
        verify_time: 3.5,
        peak_memory: 1344,
        proof_size: 552,
      },
      {
        id: 2,
        prover_name: 'Alpha,algo 2',
        proof_system: 'Alpha',
        algorithm: 'algo 2',
        status: 'running',
        setup_time: 6.5,
        witness_generation_time: 3.5,
        proof_generation_time: 8.5,
        verify_time: 5.5,
        peak_memory: 1544,
        proof_size: 542,
      },
      {
        id: 3,
        prover_name: 'Alpha,algo 3',
        proof_system: 'Alpha',
        algorithm: 'algo 3',
        status: 'completed',
        setup_time: 12.5,
        witness_generation_time: 6.5,
        proof_generation_time: 10.5,
        verify_time: 3.5,
        peak_memory: 1644,
        proof_size: 202,
      },
      {
        id: 4,
        prover_name: 'Beta,algo 1',
        proof_system: 'Beta',
        algorithm: 'algo 1',
        status: 'completed',
        setup_time: 14.5,
        witness_generation_time: 6.5,
        proof_generation_time: 10.5,
        verify_time: 3.5,
        peak_memory: 1244,
        proof_size: 202,
      },
      {
        id: 5,
        prover_name: 'Beta,algo 2',
        proof_system: 'Beta',
        algorithm: 'algo 2',
        status: 'completed',
        setup_time: 16.5,
        witness_generation_time: 2.5,
        proof_generation_time: 6.5,
        verify_time: 7.5,
        peak_memory: 1104,
        proof_size: 502,
      },
      {
        id: 6,
        prover_name: 'Gamma,algo 1',
        proof_system: 'Gamma',
        algorithm: 'algo 1',
        status: 'completed',
        setup_time: 14.5,
        witness_generation_time: 2.5,
        proof_generation_time: 6.5,
        verify_time: 7.5,
        peak_memory: 1404,
        proof_size: 402,
      },
      {
        id: 7,
        prover_name: 'Gamma,algo 2',
        proof_system: 'Gamma',
        algorithm: 'algo 2',
        status: 'completed',
        setup_time: 11.5,
        witness_generation_time: 2.5,
        proof_generation_time: 6.5,
        verify_time: 7.5,
        peak_memory: 1484,
        proof_size: 502,
      },
    ],
  },
  {
    id: 1005,
    execution_number: 3600,
    problem_name: 'Poseidon2 Hash BN254',
    user_name: 'Polyhedra Network',
    description: '',
    user_avatar: 'user_avatar_svg',
    create_time: 'Jul 15, 2024, 18:59:53 (UTC+08:00)',
    // desc: '--',
    submissionsTableData: [
      {
        id: 1,
        prover_name: 'Alpha,algo 1',
        proof_system: 'Alpha',
        algorithm: 'algo 1',
        status: 'pending',
        setup_time: 3.5,
        witness_generation_time: 3.5,
        proof_generation_time: 3.5,
        verify_time: 3.5,
        peak_memory: 644,
        proof_size: 342,
      },
      {
        id: 2,
        prover_name: 'Alpha,algo 2',
        proof_system: 'Alpha',
        algorithm: 'algo 2',
        status: 'running',
        setup_time: 6.5,
        witness_generation_time: 3.5,
        proof_generation_time: 8.5,
        verify_time: 5.5,
        peak_memory: 1044,
        proof_size: 442,
      },
      {
        id: 3,
        prover_name: 'Alpha,algo 3',
        proof_system: 'Alpha',
        algorithm: 'algo 3',
        status: 'completed',
        setup_time: 10.5,
        witness_generation_time: 6.5,
        proof_generation_time: 10.5,
        verify_time: 3.5,
        peak_memory: 1644,
        proof_size: 202,
      },
      {
        id: 4,
        prover_name: 'Beta,algo 1',
        proof_system: 'Beta',
        algorithm: 'algo 1',
        status: 'completed',
        setup_time: 12.5,
        witness_generation_time: 6.5,
        proof_generation_time: 10.5,
        verify_time: 3.5,
        peak_memory: 1344,
        proof_size: 202,
      },
      {
        id: 5,
        prover_name: 'Beta,algo 2',
        proof_system: 'Beta',
        algorithm: 'algo 2',
        status: 'completed',
        setup_time: 16.5,
        witness_generation_time: 2.5,
        proof_generation_time: 6.5,
        verify_time: 7.5,
        peak_memory: 1464,
        proof_size: 402,
      },
      {
        id: 6,
        prover_name: 'Gamma,algo 1',
        proof_system: 'Gamma',
        algorithm: 'algo 1',
        status: 'completed',
        setup_time: 14.5,
        witness_generation_time: 2.5,
        proof_generation_time: 6.5,
        verify_time: 7.5,
        peak_memory: 1404,
        proof_size: 202,
      },
      {
        id: 7,
        prover_name: 'Gamma,algo 2',
        proof_system: 'Gamma',
        algorithm: 'algo 2',
        status: 'completed',
        setup_time: 11.5,
        witness_generation_time: 2.5,
        proof_generation_time: 6.5,
        verify_time: 7.5,
        peak_memory: 1604,
        proof_size: 602,
      },
    ],
  },
];
