#!/bin/bash

npx lint-staged --allow-empty 

gitleaks detect --source . --no-git

WANTED_EMAIL_SUFFIX=polyhedra.network
CURR_EMAIL=`git config --get user.email`
DESIRED_AUTHOR_EMAIL=me@polyhedra.network

if [[ ${CURR_EMAIL} != *@${WANTED_EMAIL_SUFFIX} ]]; then
  echo "NOTICE: Current email is ${CURR_EMAIL}"
  echo -e "NOTICE: Incorrect public committer email.  Run commit again like this:\nGIT_AUTHOR_EMAIL=${DESIRED_AUTHOR_EMAIL} git commit -m \"<YOUR MESSAGE>\""
  exit 1
fi